Author/urls.py
from django.urls import path
from . import views
from enterprise.views import ServiceCreateView, ServiceListView

app_name = 'author'

urlpatterns = [
    path('', views.ProfileList.as_view(), name='profile-list'),
    path('profile/add', views.ProfileFamilyMemberCreate.as_view(), name='profile-add'),
    path('profile/<pk>/update', views.ProfileFamilyMemberUpdate.as_view(), name='profile-update'),
    path('profile/<pk>/delete', views.ProfileDelete.as_view(), name='profile-delete'),


    path('enterprise/add', ServiceCreateView.as_view(), name='enterprise-add'),
    path('enterprise', ServiceListView.as_view(), name='enterprise-list'),
    
]

learningformset/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Author.urls', namespace='author')),
]

Author/models.py
from __future__ import unicode_literals
from django.urls import reverse

from django.db import models
from django.utils import timezone


class Profile(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse('author:profile-update', kwargs={'pk': self.pk})

    def __unicode__(self):
        return "%s %s" % (self.first_name, self.last_name)


class FamilyMember(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    relationship = models.CharField(max_length=100)

    def __str__(self):
        return self.relationship

enterprise/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Service(models.Model):
    name = models.CharField(max_length=100)
    linked_companies = models.ManyToManyField(Company)

    def __str__(self):
        return self.name

Author/forms.py
from django.forms import ModelForm, inlineformset_factory

from .models import Profile, FamilyMember


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ()


class FamilyMemberForm(ModelForm):
    class Meta:
        model = FamilyMember
        exclude = ()


FamilyMemberFormSet = inlineformset_factory(Profile, FamilyMember,
                                            form=FamilyMemberForm, extra=1)

enterprise/forms.py
from django import forms
from django.forms import ModelForm
from .models import Service

class ServiceForm(ModelForm):
    class Meta:
        model = Service
        fields = '__all__'

        widgets = {
            'linked_companies' : forms.CheckboxSelectMultiple()
        }

Author/views.py
from django.urls import reverse_lazy
from django.db import transaction
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from .models import Profile
from .forms import FamilyMemberFormSet


class ProfileList(ListView):
    model = Profile


class ProfileCreate(CreateView):
    model = Profile
    fields = ['first_name', 'last_name']


class ProfileFamilyMemberCreate(CreateView):
    model = Profile
    fields = ['first_name', 'last_name']

    def get_context_data(self, **kwargs):
        data = super(ProfileFamilyMemberCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['familymembers'] = FamilyMemberFormSet(self.request.POST)
        else:
            data['familymembers'] = FamilyMemberFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        familymembers = context['familymembers']
        with transaction.atomic():
            self.object = form.save()

            if familymembers.is_valid():
                familymembers.instance = self.object
                familymembers.save()
        return super(ProfileFamilyMemberCreate, self).form_valid(form)


class ProfileUpdate(UpdateView):
    model = Profile
    success_url = '/'
    fields = ['first_name', 'last_name']


class ProfileFamilyMemberUpdate(UpdateView):
    model = Profile
    fields = ['first_name', 'last_name']
    

    def get_context_data(self, **kwargs):
        data = super(ProfileFamilyMemberUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['familymembers'] = FamilyMemberFormSet(self.request.POST, instance=self.object)
        else:
            data['familymembers'] = FamilyMemberFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        familymembers = context['familymembers']
        with transaction.atomic():
            self.object = form.save()

            if familymembers.is_valid():
                familymembers.instance = self.object
                familymembers.save()
        return super(ProfileFamilyMemberUpdate, self).form_valid(form)


class ProfileDelete(DeleteView):
    model = Profile
    success_url = reverse_lazy('author:profile-list')

enterprise/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, View
from django.views.generic.list import ListView
from .models import Service
from .forms import ServiceForm
from django.urls import reverse_lazy


class ServiceCreateView(CreateView):
    model = Service
    template_name = "enterprise/service_new.html"
    form_class = ServiceForm
    success_message = "Endereço e Contatos alterados com sucesso!"

    def get_success_url(self):
        return reverse_lazy('author:enterprise-list')


class ServiceListView(ListView):
    model = Service
    template_name = "enterprise/service_list.html"

# Create your views here.

Author/templates/Author/profile_confirm_delete.html
{% extends "base.html" %}

{% block title %}{% endblock %}
{% block content %}
    <h2></h2>
    <hr>
    <div>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm"/>
        </form>
    </div>
{% endblock %}

Author/templates/Author/profile_form.html
{% load static %}

<div class="col-md-4">
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}

        <table class="table">
            {{ familymembers.management_form }}

            {% for form in familymembers.forms %}
                {% if forloop.first %}
                    <thead>
                    <tr>
                        {% for field in form.visible_fields %}
                            <th>{{ field.label|capfirst }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                {% endif %}
                <tr class="{% cycle 'row1' 'row2' %} formset_row">
                    {% for field in form.visible_fields %}
                        <td>
                            {# Include the hidden fields in the form #}
                            {% if forloop.first %}
                                {% for hidden in form.hidden_fields %}
                                    {{ hidden }}
                                {% endfor %}
                            {% endif %}
                            {{ field.errors.as_ul }}
                            {{ field }}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
        <input type="submit" value="Save"/> <a href="{% url 'author:profile-list' %}">back to the list</a>
    </form>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'formset/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row').formset({
        addText: 'add family member',
        deleteText: 'remove',
        prefix: 'familymember_set'
    });
</script>

Author/templates/Author/profile_list.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}

    <h2>Here are all user profiles: </h2>
    <div>
        <ul>
            {% for profile in object_list %}
                <li>{{ profile.first_name }} {{ profile.last_name }} | <a
                        href="{% url 'author:profile-update' profile.pk %}">edit</a>
                    <a href="{% url 'author:profile-delete' profile.pk %}">delete</a>
                </li>
            {% empty %}
                <li>No profile yet.</li>
            {% endfor %}

        </ul>
        <p>
            <a href="{% url 'author:profile-add' %}">add a profile</a>
        </p>
    </div>
{% endblock %}

Author/templates/base.html
<html lang="en">
<head>
    <title>{% block title %}My amazing site{% endblock %}</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>

<body>
<div id="content" class="container">
    <div class="md-col-10">
        {% block content %}{% endblock %}
    </div>

</div>
</body>
</html>

enterprise/templates/enterprise/service_list.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}

    <h2>Here are all user profiles: </h2>
    <div>
        <ul>
            {% for service in object_list %}
                <li>Name: {{ service.name }} | 
                    
                    Company: {% for area in service.linked_companies.all %} {{area}}{% endfor %}
                    
                </li>
            {% empty %}
                <li>No profile yet.</li>
            {% endfor %}

        </ul>
        <p>
        </p>
    </div>
{% endblock %}

enterprise/templates/enterprise/service_new.html
{% load static %}

<div class="col-md-4">
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Save"/> <a href="{% url 'author:profile-list' %}">back to the list</a>
    </form>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'formset/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row').formset({
        addText: 'add family member',
        deleteText: 'remove',
        prefix: 'familymember_set'
    });
</script>